apiVersion: apps/v1
kind: Deployment
metadata:
  name: jenkins-deployments 
  labels:
    app: Jenkins
spec:
  template:
    metadata:
      name: jenkins-pod
      labels:
        app: jenkins
    spec:
      containers:
        - name: jenkins
          image: jenkins
          
      volumes: 
        - 
          hostPath: 
            path: /var/run
          name: docker-sock
        - 
          hostPath: 
            path: /var/jenkins_home
          name: jenkins-home
  replicas: 3
  selector:
    matchLabels:
      app: jenkins
