appVersion: apps\v1
kind: Deployment
metadata:
  name: jenkins-deployment
  labels:
    app: Jenkins
spec:
  template:
    metadata:
      name: jenkins-pod
      lables:
        app: jenkins
    spec:
      containers:
        -name: jenkins
        image: jenkins
  replicas: 3
  selectors:
    matchLabels:
      app: Jenkins
