---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: jenkins-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: jenkins
  template:
    metadata:
      labels:
        app: jenkins
      name: jenkins-pod
    spec:
      containers:
        -
          image: "suvenkar/jenkins:5"
          name: jenkins
          ports:
            -
              containerPort: 8080
volumeMounts:
  -
    mountPath: /var/jenkins_home
    name: jenkins-home
    volumes:
      -
        emptyDir: {}
        name: jenkins-home
