apiVersion: apps/v1
kind: Deployment
metadata:
  name: tomcat-deployments
  labels:
    app: Tomcat
spec:
  template:
    metadata:
      name: tomcat-pod
      labels:
        app: tomcat
    spec:
      containers:
        - name: tomcat
          image: tomcat
  replicas: 3
  selector:
    matchLabels:
      app: tomcat
